### PR TITLE
Add Node.js release schedule

### PR DESCRIPTION
**Pull request by vostrik**
Add Node.js release schedule according to this issue from browserslist:
https://github.com/browserslist/browserslist/issues/75

### CODE REVIEW

**Comment by ai** [comment]
Should we normalize JSON in this package?

**Comment by vostrik** [comment]
This question for me or for @chicoxyzzy ? Excuse me, don't understand :)

**Comment by chicoxyzzy** [comment]
@ai do you mean changes in https://github.com/chicoxyzzy/node-releases/pull/2/files#diff-7cea08e9ebf9d883a3470167b9847dc3 (made by https://github.com/chicoxyzzy/node-releases/pull/2/files#diff-2abba6afacec5511aa533482df8a3b64L27)? If yes, then I'm not sure it has any value. This data is only needed for machines, not humans, so we can probably save some bytes. Though I don't have any strong opinion on that

**Comment by ai** [comment]
@chicoxyzzy up to you. It was just a suggestion. If a format is OK for you. Let’s keep it.

**Comment by chicoxyzzy** [comment]
@ai you mean https://github.com/chicoxyzzy/node-releases/pull/2/files#diff-d23bac319c5786b53da435925e1b09ca? Yes, it's different from previous data. It's from another source and it contains additional info about major releases.

**Pull request merged**
