### PR TITLE
build: Add nightly sync

### LINKED ISSUE #3: Implement automatic data updates
Idea: implement bot which will create new PR for review based on information from [CI daily cron job](https://docs.travis-ci.com/user/cron-jobs/). Not sure if it's possible. We should check. Other ideas are welcome.

### PR DESCRIPTION
**Pull request by nschonni**
Fixes #3

### CODE REVIEW

**Comment by nschonni** [comment]
This was just something I lifted from a different PR, but I haven't really tested it out, so it probably will need some testing if this lands

**Comment by chicoxyzzy** [comment]
That's awesome! Thank you! Can't wait to test this on weekend

**Comment by nschonni** [comment]
Removed the caching since it doesn't work right now on cron jobs. Also swapped to an Action for the commit so it doesn't fail if there are no changes

**Comment by chicoxyzzy** [comment]
Let's try this!

**Comment by chicoxyzzy** [comment]
Thank you @nschonni! Works like a charm!

**Comment by nschonni** [comment]
Cool, might be worth trying to add a tag an NPM publish too. Don't have experience in those though :)

**Comment by chicoxyzzy** [comment]
It should be pretty easy. I'll add publish feature later.

**Pull request merged**
